dist: xenial
language: go

node_js:
  - lts/*

go:
  - "1.11"

before_install:
  - go get github.com/nats-io/nats-server
  - nohup gnatsd > /dev/null 2>&1 &

install: npm i

script: node_modules/.bin/nyc npm test && node_modules/.bin/nyc report --reporter=text-lcov | node_modules/.bin/coveralls
